twillio:
  TWILIO_ACCOUNT_SID: ACe0467f2a2a3a0b732158c8f82a06f1f3
  TWILIO_AUTH_TOKEN: 208250eafa6adf1c07695032ec3e0ae9

callback:
  url: https://notification-bridge.herokuapp.com/api/v1/notification-bridge-callback

quarkus:
  hibernate-orm:
    database:
      generation: drop-and-create

  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}

  http:
    port: ${PORT:8080}